version: '3'
services:
    provider:
        build: .
        ports:
            - "8090:7000"
        volumes:
            - /home/devbnjhp/nodejs/data/:/usr/src/app/data/
        networks:
            - sara

# Docker Networks
networks:
    sara:
        driver: bridge