version: '3'
services:
    provider:
        build: .
        ports:
            - "8090:7000"
        volumes:
            - .:/sara
        networks:
            - sara

# Docker Networks
networks:
    sara:
        driver: bridge